export const initialEdges = [
  {
    id: "org1-crypto",
    source: "org1",
    target: "cryptodrop",
    type: "gradient",
    animated: true,
    data: { color: "#0284c7" },
    style: { strokeWidth: 2 },
  },
  {
    id: "org2-crypto",
    source: "org2",
    target: "cryptodrop",
    type: "gradient",
    animated: true,
    data: { color: "#0369a1" },
    style: { strokeWidth: 2 },
  },
  {
    id: "org3-crypto",
    source: "org3",
    target: "cryptodrop",
    type: "gradient",
    animated: true,
    data: { color: "#075985" },
    style: { strokeWidth: 2 },
  },
  {
    id: "crypto-complexity",
    source: "cryptodrop",
    target: "complexity",
    type: "gradient",
    animated: true,
    data: { color: "#7c3aed" },
    style: { strokeWidth: 2 },
  },
  {
    id: "crypto-quality",
    source: "cryptodrop",
    target: "quality",
    type: "gradient",
    animated: true,
    data: { color: "#6d28d9" },
    style: { strokeWidth: 2 },
  },
  {
    id: "crypto-techstack",
    source: "cryptodrop",
    target: "techstack",
    type: "gradient",
    animated: true,
    data: { color: "#5b21b6" },
    style: { strokeWidth: 2 },
  },
  {
    id: "crypto-discussions",
    source: "cryptodrop",
    target: "discussions",
    type: "gradient",
    animated: true,
    data: { color: "#4c1d95" },
    style: { strokeWidth: 2 },
  },
  {
    id: "crypto-codesmells",
    source: "cryptodrop",
    target: "codesmells",
    type: "gradient",
    animated: true,
    data: { color: "#2e1065" },
    style: { strokeWidth: 2 },
  },
  {
    id: "crypto-spam",
    source: "cryptodrop",
    target: "spam",
    type: "gradient",
    animated: true,
    data: { color: "#4338ca" },
    style: { strokeWidth: 2 },
  },
  {
    id: "complexity-score",
    source: "complexity",
    target: "score",
    type: "gradient",
    animated: true,
    data: { color: "#059669" },
    style: { strokeWidth: 2 },
  },
  {
    id: "quality-score",
    source: "quality",
    target: "score",
    type: "gradient",
    animated: true,
    data: { color: "#047857" },
    style: { strokeWidth: 2 },
  },
  {
    id: "techstack-score",
    source: "techstack",
    target: "score",
    type: "gradient",
    animated: true,
    data: { color: "#065f46" },
    style: { strokeWidth: 2 },
  },
  {
    id: "discussions-score",
    source: "discussions",
    target: "score",
    type: "gradient",
    animated: true,
    data: { color: "#047857" },
    style: { strokeWidth: 2 },
  },
  {
    id: "codesmells-score",
    source: "codesmells",
    target: "score",
    type: "gradient",
    animated: true,
    data: { color: "#059669" },
    style: { strokeWidth: 2 },
  },
  {
    id: "spam-score",
    source: "spam",
    target: "score",
    type: "gradient",
    animated: true,
    data: { color: "#065f46" },
    style: { strokeWidth: 2 },
  },
  {
    id: "score-attestation",
    source: "score",
    target: "attestation",
    type: "gradient",
    animated: true,
    data: { color: "#ea580c" },
    style: { strokeWidth: 2 },
  },
  {
    id: "attestation-walrus",
    source: "attestation",
    target: "walrus",
    type: "gradient",
    animated: true,
    data: { color: "#c2410c" },
    style: { strokeWidth: 2 },
  },
  {
    id: "walrus-leaderboard",
    source: "walrus",
    target: "leaderboard",
    type: "gradient",
    animated: true,
    data: { color: "#9a3412" },
    style: { strokeWidth: 2 },
  },
];

export const initialNodes = [
  // {
  //   id: "org1",
  //   type: "customNode",
  //   data: {
  //     label: "Organisation 1",
  //     rippleColor: "#0062D1",
  //     color: "#0062D1",
  //     hierarchy: "PARENT",
  //   },
  //   position: { x: 0, y: -100 },
  // },
  {
    id: "org2",
    type: "customNode",
    data: { label: "Organisation", hierarchy: "PARENT" },
    position: { x: 0, y: 150 },
  },
  // {
  //   id: "org3",
  //   type: "customNode",
  //   data: { label: "Organisation 3", hierarchy: "PARENT" },
  //   position: { x: 0, y: 400 },
  // },
  {
    id: "cryptodrop",
    type: "customNode",
    data: { label: "Airdrop Sentinel", hierarchy: "MIDDLE" },
    position: { x: 160, y: 151 },
  },
  {
    id: "complexity",
    type: "customNode",
    data: { label: "Complexity Analysis", hierarchy: "CHILD" },
    position: { x: 450, y: 0 },
  },
  {
    id: "quality",
    type: "customNode",
    data: { label: "Quality Check", hierarchy: "CHILD" },
    position: { x: 450, y: 60 },
  },
  {
    id: "techstack",
    type: "customNode",
    data: { label: "Tech Stack Eval", hierarchy: "CHILD" },
    position: { x: 450, y: 120 },
  },
  {
    id: "discussions",
    type: "customNode",
    data: { label: "Discussions Analysis", hierarchy: "CHILD" },
    position: { x: 450, y: 180 },
  },
  {
    id: "codesmells",
    type: "customNode",
    data: { label: "Code Smells", hierarchy: "CHILD" },
    position: { x: 450, y: 240 },
  },
  {
    id: "spam",
    type: "customNode",
    data: { label: "Spam Detection", hierarchy: "CHILD" },
    position: { x: 450, y: 300 },
  },
  {
    id: "score",
    type: "customNode",
    data: { label: "Score & Analysis", hierarchy: "MIDDLE" },
    position: { x: 650, y: 151 },
  },
  {
    id: "attestation",
    type: "customNode",
    data: { label: "Attestation", hierarchy: "MIDDLE" },
    position: { x: 850, y: 150 },
  },
  {
    id: "walrus",
    type: "customNode",
    data: { label: "Walrus", hierarchy: "MIDDLE" },
    position: { x: 990, y: 149 },
  },
  {
    id: "leaderboard",
    type: "customNode",
    data: { label: "Leaderboard & Mailing List", hierarchy: "LASTCHILD" },
    position: { x: 1150, y: 150 },
  },
];
