import { color } from "framer-motion";

export const initialEdges = [
  {
    id: "org1-crypto",
    source: "org1",
    target: "cryptodrop",
    type: "gradient",
    animated: true,
    data: { color: "#0062D1" },
    style: { strokeWidth: 2 },
  },
  {
    id: "org2-crypto",
    source: "org2",
    target: "cryptodrop",
    type: "gradient",
    animated: true,
    data: { color: "#0062D1" },
    style: { strokeWidth: 2 },
  },
  {
    id: "org3-crypto",
    source: "org3",
    target: "cryptodrop",
    type: "gradient",
    animated: true,
    data: { color: "#0062D1" },
    style: { strokeWidth: 2 },
  },
  {
    id: "crypto-agent1",
    source: "cryptodrop",
    target: "agent1",
    type: "gradient",
    animated: true,
    data: { color: "#763DA9" },
    style: { strokeWidth: 2 },
  },
  {
    id: "crypto-agent2",
    source: "cryptodrop",
    target: "agent2",
    type: "gradient",
    animated: true,
    data: { color: "#763DA9" },
    style: { strokeWidth: 2 },
  },
  {
    id: "crypto-agent3",
    source: "cryptodrop",
    target: "agent3",
    type: "gradient",
    animated: true,
    data: { color: "#763DA9" },
    style: { strokeWidth: 2 },
  },
  {
    id: "agent1-score",
    source: "agent1",
    target: "score",
    type: "gradient",
    animated: true,
    data: { color: "#0062D1" },
    style: { strokeWidth: 2 },
  },
  {
    id: "agent2-score",
    source: "agent2",
    target: "score",
    type: "gradient",
    animated: true,
    data: { color: "#0062D1" },
    style: { strokeWidth: 2 },
  },
  {
    id: "agent3-score",
    source: "agent3",
    target: "score",
    type: "gradient",
    animated: true,
    data: { color: "#0062D1" },
    style: { strokeWidth: 2 },
  },
  {
    id: "score-attestation",
    source: "score",
    target: "attestation",
    type: "gradient",
    animated: true,
    data: { color: "#0D8C7D" },
    style: { strokeWidth: 2 },
  },
  {
    id: "attestation-walrus",
    source: "attestation",
    target: "walrus",
    type: "gradient",
    animated: true,
    data: { color: "#0D8C7D" },
    style: { strokeWidth: 2 },
  },
  {
    id: "walrus-leaderboard",
    source: "walrus",
    target: "leaderboard",
    type: "gradient",
    animated: true,
    data: { color: "#0D8C7D" },
    style: { strokeWidth: 2 },
  },
];
export const initialNodes = [
  {
    id: "org1",
    type: "customNode",
    data: {
      label: "Organisation 1",
      rippleColor: "#0062D1",
      color: "#0062D1",
      hierarchy: "PARENT",
    },
    position: { x: 0, y: -100 },
  },
  {
    id: "org2",
    type: "customNode",
    data: { label: "Organisation 2", hierarchy: "PARENT" },
    position: { x: 0, y: 150 },
  },
  {
    id: "org3",
    type: "customNode",
    data: { label: "Organisation 3", hierarchy: "PARENT" },
    position: { x: 0, y: 400 },
  },
  {
    id: "cryptodrop",
    type: "customNode",
    data: { label: "Crypto Drop", hierarchy: "MIDDLE" },
    position: { x: 250, y: 151 },
  },
  {
    id: "agent1",
    type: "customNode",
    data: { label: "Agent 1", hierarchy: "CHILD" },
    position: { x: 450, y: 25 },
  },
  {
    id: "agent2",
    type: "customNode",
    data: { label: "Agent 2", hierarchy: "CHILD" },
    position: { x: 450, y: 150 },
  },
  {
    id: "agent3",
    type: "customNode",
    data: { label: "Agent 3", hierarchy: "CHILD" },
    position: { x: 450, y: 275 },
  },
  {
    id: "score",
    type: "customNode",
    data: { label: "Score & Analysis", hierarchy: "MIDDLE" },
    position: { x: 650, y: 151 },
  },
  {
    id: "attestation",
    type: "customNode",
    data: { label: "Attestation", hierarchy: "MIDDLE" },
    position: { x: 850, y: 150 },
  },
  {
    id: "walrus",
    type: "customNode",
    data: { label: "Walrus", hierarchy: "MIDDLE" },
    position: { x: 990, y: 149 },
  },
  {
    id: "leaderboard",
    type: "customNode",
    data: { label: "Leaderboard & Mailing List", hierarchy: "LASTCHILD" },
    position: { x: 1150, y: 150 },
  },
];
